mode: "bert-training-inference-b_evaluation"
version_name: "spa"

# bert mode, source data
trainset_path: "Data_example/bert/train.csv"
testset_path: "Data_example/bert/test.csv"
evalset_path: "Data_example/bert/valid.csv"

# incremental mode
# meta_path: list or list of list (several paths), * 'rid' should appear in meta_path if it is setted
meta_path: ["name", "rid"]

kafka:
  topicid: "entity_resolution_process"
  groupid: "er_group"
  bootstrap_servers: "localhost"
  port: 9092

# STATE MANAGEMENT
state_management:
# bert mode
  bert-dir: "/app/data/bert"
# incremental mode. if execute several config files successively, the embedding_model-name (or version name) can not be the same
  graph-dir: "/app/data/graph"
  graph-name: ""
  embedding-dir: "/app/data/embedding"
  embedding_model-name: ""
  feature_index-dir: "/app/data/index"
  feature_index-name: ""
  predicted_match-dir: "/app/data/predicted"
  predicted_match-name: ""

# pipeline
normalization:

graph_construction:

random_walk:

embedding_training:

bert_training:

cg_feature_extraction:

feature_index_construction:

candidate_enumeration:

calculating_similarity:

decision_making:

bert_inference:

evaluation:

b_evaluation:
