### Mandatory
mode: "bert-training-evaluation"
version_name: "spa"

# bert mode, source data
# The static NFS dataset volume is mounted at /data.
trainset_path: "/data/exp_datasets/2-fordors_zagats/train.csv"
testset_path: "/data/exp_datasets/2-fordors_zagats/test.csv"
evalset_path: "/data/exp_datasets/2-fordors_zagats/valid.csv"
# STATE MANAGEMENT
state_management:
# bert mode
  bert-dir: "/app/data/bert"
# incremental mode. if execute several config files successively, the embedding_model-name (or version name) can not be the same
  graph-dir: "/app/data/graph"
  graph-name: ""
  embedding-dir: "/app/data/embedding"
  embedding_model-name: ""
  feature_index-dir: "/app/data/index"
  feature_index-name: ""
  predicted_match-dir: "/app/data/predicted"
  predicted_match-name: ""

### Optional
# pipeline
normalization:

graph_construction:

random_walk:

embedding_training:

bert_training:

cg_feature_extraction:

feature_index_construction:

candidate_enumeration:

calculating_similarity:

decision_making:

bert_inference:

evaluation:

b_evaluation:
